<?php

/**
 * @file
 * Hook implementations for Facebook Instant Articles Display module.
 */

use Facebook\InstantArticles\Elements\Author;
use Facebook\InstantArticles\Elements\Header;
use Facebook\InstantArticles\Elements\InstantArticle;
use Facebook\InstantArticles\Elements\Time;
use Facebook\InstantArticles\Elements\Image;
use Facebook\InstantArticles\Transformer\Transformer;
use Facebook\InstantArticles\Elements\Paragraph;
use Facebook\InstantArticles\Elements\Element;
use Facebook\InstantArticles\Elements\Footer;
use Facebook\InstantArticles\Elements\Blockquote;
use Facebook\InstantArticles\Elements\Pullquote;

const FB_INSTANT_ARTICLES_VERSION = '0.1.0';

/**
* Implements hook_init().
*/
function fb_instant_articles_display_init() {
 // Configure Instant Articles Transformer logger to append to Drupal log if enabled
 $enable_transformer_logging = variable_get('fb_instant_articles_display_enable_transformer_logging', FALSE);
 \Logger::configure(
   array(
     'rootLogger' => array(
       'appenders' => array('facebook-instantarticles-transformer')
     ),
     'appenders' => array(
       'facebook-instantarticles-transformer' => array(
         'class' => $enable_transformer_logging ? 'LoggerAppenderDrupal' : 'LoggerAppenderNull',
         'layout' => array(
           'class' => 'LoggerLayoutSimple'
         )
       )
     )
   )
 );
}

/**
 * Implements hook_menu().
 */
function fb_instant_articles_display_menu() {
  // Top level configuration page.
  $items['admin/config/services/fb-instant-articles/display'] = array(
    'title' => 'Facebook Instant Articles Display',
    'description' => 'Display settings for Facebook Instant Articles.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fb_instant_articles_display_admin_settings_form'),
    'access arguments' => array('administer fb_instant_articles_display'),
    'file' => 'includes/admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function fb_instant_articles_display_permission() {
  $permissions = array();

  $permissions['administer fb_instant_articles_display'] = array(
    'title' => t('Administer Facebook Instant Articles Display'),
  );
  return $permissions;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function fb_instant_articles_display_form_node_type_form_alter(&$form, &$form_state) {
  // Add a vertical tab to the node type form.
  if (user_access('administer fb_instant_articles_display')) {
    // Build fieldset for vertical tab section.
    $fieldset = array(
      '#type' => 'fieldset',
      '#title' => t('Facebook Instant Articles'),
      '#description' => t('Configure content type for Facebook Instant Article mappings.'),
      '#group' => 'additional_settings',
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
    );

    // Has the section already been created (perhaps by a sub module)?
    if (isset($form['fb_instant_articles_display'])) {
      // Add additional fieldset data.
      $form['fb_instant_articles_display'] += $fieldset;
    }
    // Else, create the fieldset.
    else {
      $form['fb_instant_articles_display'] = $fieldset;
    }

    // Is an Article type?
    $type = $form['#node_type']->type;
    $fb_instant_enabled = fb_instant_articles_display_is_article_type('node', $type);

    $previously_checked = (isset($form_state['values']) && $form_state['values']['fb_instant_articles_display']['fb_instant_enabled']);

    // Build the product checkbox.
    $form['fb_instant_articles_display']['fb_instant_enabled'] = array(
      '#type' => 'checkbox',
      '#title' => t('Include Content Type in Facebook Instant Articles feed.'),
      '#description' => t('Enable content of this type to be included in the Facebook Instant Articles feed.'),
      '#weight' => 0,
      '#default_value' => ($previously_checked || $fb_instant_enabled) ? TRUE : FALSE,
    );

    // Add custom submit.
    $form['#submit'][] = 'fb_instant_articles_display_node_type_form_submit';
  }
}

/**
 * Submit callback for node type form.
 */
function fb_instant_articles_display_node_type_form_submit($form, &$form_state) {
  $fb_instant_enabled = fb_instant_articles_display_is_article_type('node', $form['#node_type']->type);
  if (!$fb_instant_enabled && $form_state['values']['fb_instant_enabled']) {
    // Save the new article type.
    fb_instant_articles_display_set_entity_type('node', $form['#node_type']->type);
    ctools_include('export');
    ctools_export_crud_enable('fb_instant_articles_display_layout_settings', 'node|article|fb_instant_article');
  }
  // Delete existing settings.
  elseif (!$form_state['values']['fb_instant_enabled']) {
    fb_instant_articles_display_delete_entity_type('node', $form['#node_type']->type);
  }
}

/**
 * Checks if an entity type and bundle are a Facebook Instant Article type.
 *
 * @param string $entity_type
 *   The entity type name.
 * @param string $bundle
 *   The entity bundle name.
 *
 * @return bool
 *   Boolean TRUE or FALSE.
 */
function fb_instant_articles_display_is_article_type($entity_type, $bundle) {
  $is_type = FALSE;
  if ($types = fb_instant_articles_display_get_article_entity_types()) {
    // See if this entity type and bundle exists.
    if (isset($types[$entity_type]) && isset($types[$entity_type][$bundle])) {
      $is_type = TRUE;
    }
  }
  // Allow other modules to alter.
  drupal_alter('fb_instant_articles_display_is_article_type', $is_type, $entity_type, $bundle);

  return $is_type;
}

/**
 * Gets entity types that are treated as Facebook Instant Articles.
 *
 * @return mixed
 *   Array of entity types and bundles.
 */
function fb_instant_articles_display_get_article_entity_types() {
  $entity_types = &drupal_static(__FUNCTION__);
  // Entity types not retrieved yet?
  if (!isset($entity_types)) {
    $results = db_select('fb_instant_articles_display_entity_types', 'fbaet')
      ->fields('fbaet')
      ->execute();
    // Loop through each of the retrieved entity types.
    foreach ($results as $result) {
      $entity_types[$result->entity_type][$result->entity_bundle] = array(
        'type' => $result->entity_type,
        'bundle' => $result->entity_bundle,
      );
    }
    // Allow other modules to alter.
    drupal_alter('fb_instant_articles_display_entity_types', $entity_types);
  }
  return $entity_types;
}

/**
 * Sets the entity type as an allowable Facebook Instant Article type.
 *
 * @param string $type
 *   The entity type.
 * @param string $bundle
 *   The entity bundle.
 */
function fb_instant_articles_display_set_entity_type($type, $bundle) {
  db_insert('fb_instant_articles_display_entity_types')
    ->fields(array(
      'entity_type' => $type,
      'entity_bundle' => $bundle,
    ))
    ->execute();
  // Allow other modules to perform actions.
  module_invoke_all('fb_instant_articles_display_set_type', $type, $bundle);
}

/**
 * Deletes the entity type as an allowable Facebook Instant Article type.
 *
 * @param string $type
 *   The entity type.
 * @param string $bundle
 *   The entity bundle.
 */
function fb_instant_articles_display_delete_entity_type($type, $bundle) {
  db_delete('fb_instant_articles_display_entity_types')
    ->condition('entity_type', $type)
    ->condition('entity_bundle', $bundle)
    ->execute();
  // Allow other modules to perform actions.
  module_invoke_all('fb_instant_articles_display_delete_type', $type, $bundle);
}

/**
 * Implements hook_entity_info_alter().
 */
function fb_instant_articles_display_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['fb_instant_article'] = array(
    'label' => t('Facebook Instant Articles'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_node_load().
 */
function fb_instant_articles_display_node_load($nodes, $types) {
  $enabled_entity_types = fb_instant_articles_display_get_article_entity_types();
  $enabled_node_types = array_keys($enabled_entity_types['node']);
  if (count(array_intersect($enabled_node_types, $types))) {
    foreach ($nodes as $node) {
      // Load and store the layout_settings, which maps fields to Facebook Instant
      // Articles settings.
      $node->fb_instant_articles_display_layout_settings = fb_instant_articles_display_get_node_layout_settings($node->type);

      // InstantArticle object for the node.  This will be built up by any field
      // formatters and rendered out in hook_preprocess_node().
      $instant_article = InstantArticle::create()
        ->addMetaProperty('op:generator:application', 'drupal/fb_instant_articles')
        ->addMetaProperty('op:generator:application:version', FB_INSTANT_ARTICLES_VERSION)
        ->withCanonicalUrl(url('node/' . $node->nid, array('absolute' => TRUE)))
        // @todo where best to store this for alter?
        ->withStyle('default');
      // InstantArticles header, at this point, only have publish an modify
      // times to add.
      $header = Header::create()
        ->withTitle($node->title)
        ->withPublishTime(
          Time::create(Time::PUBLISHED)
            ->withDatetime(
              DateTime::createFromFormat('U', $node->created)
            )
        )
        ->withModifyTime(
          Time::create(Time::MODIFIED)
            ->withDatetime(
              DateTime::createFromFormat('U', $node->changed)
            )
        );
      // Default the article autor to the username.
      $author = user_load($node->uid);
      if ($author) {
        $header->addAuthor(
          Author::create()
            ->withName($author->name)
        );
      }
      $instant_article->withHeader($header);

      // Store the InstantArticle object on the node entity to allow field
      // formatters and others to make changes/additions to it until it's finally
      // rendered out in hook_preprocess_node().
      $node->fb_instant_articles_display_instant_article = $instant_article;
    }
  }
}

/**
 * Implements hook_preprocess_node().
 */
function fb_instant_articles_display_preprocess_node(&$vars) {

  if ($vars['view_mode'] === 'fb_instant_article') {
    $vars['theme_hook_suggestions'][] = 'node__fb_instant_article';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function fb_instant_articles_display_preprocess_field(&$vars) {
  $element = $vars['element'];
  if ($element['#view_mode'] == 'fb_instant_article') {
    $vars['theme_hook_suggestions'][] = 'field__fb_instant_article';
  }
}

/**
 * Implements hook_theme().
 */
function fb_instant_articles_display_theme() {
  $theme_path = drupal_get_path('module', 'fb_instant_articles_display') . '/theme';
  return array(
    'node__fb_instant_article' => array(
      'variables' => array(),
    ),
    'field__fb_instant_article' => array(
      'template' => 'field--fb-instant-article',
      'path' => $theme_path,
      'render element' => 'element',
    ),
  );
}

/**
 * Theme function for the fb_instant_article node view mode.
 */
function theme_node__fb_instant_article($vars) {
  $node = $vars['node'];
  $content = $vars['content'];
  /** @var InstantArticle $instant_article */
  $instant_article = $node->fb_instant_articles_display_instant_article;

  // @todo just for testing, need to write a new field formater that integrates Transfomer
  $instant_article->addChild(
    Paragraph::create()
      ->appendText('Hello World!')
  );

  return $instant_article->render('<!doctype html>', TRUE);
}

/**
 * Implements hook_form_alter().
 */
function fb_instant_articles_display_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'field_ui_display_overview_form') {
    if ($form['#view_mode'] == 'fb_instant_article') {
      form_load_include($form_state, 'inc', 'fb_instant_articles_display', 'includes/view_mode_layout');
      fb_instant_articles_display_layout_form($form, $form_state);
    }
    else {
      fb_instant_articles_display_cleanup_view_mode_formatters($form);
    }
  }
}

/**
 * Get the layout settings for a specific bundle.
 */
function fb_instant_articles_display_get_node_layout_settings($bundle_name) {
  ctools_include('export');
  $export_id = 'node|' . $bundle_name . '|fb_instant_article';

  $layout_settings = ctools_export_crud_load_all('fb_instant_articles_display_layout_settings');

  $layout = new stdClass();
  if (isset($layout_settings[$export_id])) {
    $layout = $layout_settings[$export_id];
  }
  return $layout;
}

/**
 * Implements hook_field_formatter_info().
 */
function fb_instant_articles_display_field_formatter_info() {
  $formats = array();
  $formats['fbia_subtitle_formatter'] = array(
    'label' => t('FBIA Subtitle'),
    'field types' => array('text', 'text_long', 'text_with_summary'),
  );
  $formats['fbia_kicker_formatter'] = array(
    'label' => t('FBIA Kicker'),
    'field types' => array('text', 'text_long', 'text_with_summary'),
  );
  $formats['fbia_blockquote_formatter'] = array(
    'label' => t('FBIA Blockquote'),
    'field types' => array('text', 'text_long', 'text_with_summary'),
  );
  $formats['fbia_pullquote_formatter'] = array(
    'label' => t('FBIA Pullquote'),
    'field types' => array('text', 'text_long', 'text_with_summary'),
  );
  $formats['fbia_social_formatter'] = array(
    'label' => t('FBIA Social Embed'),
    'field types' => array('text', 'text_long', 'text_with_summary'),
  );
  $formats['fbia_credits_formatter'] = array(
    'label' => t('FBIA Credits'),
    'field types' => array('text', 'text_long', 'text_with_summary'),
  );
  $formats['fbia_copyright_formatter'] = array(
    'label' => t('FBIA Copyright'),
    'field types' => array('text', 'text_long', 'text_with_summary'),
  );
  $formats['fbia_author_formatter'] = array(
    'label' => t('FBIA Author'),
    'field types' => array('text', 'text_with_summary', 'list_text'),
  );
  $formats['fbia_video_formatter'] = array(
    'label' => t('FBIA Video'),
    'field types' => array('file'),
  );
  $formats['fbia_ad_formatter'] = array(
    'label' => t('FBIA Ad'),
    'field types' => array('text', 'text_long', 'text_with_summary'),
    'settings'  => array(
      'height' => '50',
      'width' => '320',
      'source' => 'url',
    ),
  );
  $formats['fbia_analytics_formatter'] = array(
    'label' => t('FBIA Analytics'),
    'field types' => array('text', 'text_long', 'text_with_summary'),
    'settings'  => array(
      'source' => 'url',
    ),
  );
  $formats['fbia_image_formatter'] = array(
    'label' => t('FBIA Image'),
    'field types' => array('image'),
    'settings'  => array(
      'style' => 'medium',
      'caption' => '',
      'likes' => '',
      'comments' => '',
      'fullscreen' => '',
    ),
  );
  $formats['fbia_interactive_formatter'] = array(
    'label' => t('FBIA Interactive'),
    'field types' => array('text', 'text_with_summary'),
    'settings'  => array(
      'height' => '50',
      'width' => 'no-margin',
    ),
  );
  $formats['fbia_list_formatter'] = array(
    'label' => t('FBIA List'),
    'field types' => array('list_text', 'list_integer', 'list_float'),
    'settings'  => array(
      'list_type' => 'ol',
    ),
  );
  return $formats;
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function fb_instant_articles_display_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {

  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $element = array();

  switch ($display['type']) {

    case 'fbia_ad_formatter':
      $element['source'] = array(
        '#type' => 'select',
        '#title' => t('Source'),
        '#description' => t('Add your ad specifying the URL or embed the full unescaped HTML.'),
        '#default_value'  => $settings['source'],
        '#options' => array(
          'url'  => t('Ad URL'),
          'embed' => t('Embedded HTML'),
        ),
      );
      $element['height'] = array(
        '#type' => 'textfield',
        '#title' => t('Height'),
        '#description' => t('Height of the iframe element.'),
        '#default_value' => $settings['height'],
      );
      $element['width'] = array(
        '#type' => 'textfield',
        '#title' => t('Width'),
        '#description' => t('Width of the iframe element.'),
        '#default_value' => $settings['width'],
      );
      break;

    case 'fbia_interactive_formatter':
      $element['height'] = array(
        '#type' => 'textfield',
        '#title' => t('Height'),
        '#description' => t('The height of your interactive graphic.'),
        '#default_value' => $settings['height'],
      );

      $element['width'] = array(
        '#type' => 'select',
        '#title' => t('Width'),
        '#description' => t('The width of your interactive graphic.'),
        '#default_value' => $settings['width'],
        '#options' => array(
          'no-margin' => t('no-margin'),
          'column-width' => t('column-width'),
        ),
      );
      break;

    case 'fbia_list_formatter':
      $element['list_type'] = array(
        '#type' => 'select',
        '#title' => t('List Type'),
        '#description' => t('Choose list type.'),
        '#default_value' => $settings['list_type'],
        '#options' => array(
          'ol' => t('Ordered'),
          'ul' => t('Unordered'),
        ),
      );
      break;

    case 'fbia_image_formatter':
      $styles = image_styles();
      $options = array();
      foreach ($styles as $style_key => $style) {
        $options[$style_key] = $style['label'];
      }
      $element['style'] = array(
        '#type' => 'select',
        '#title' => t('Style'),
        '#description' => t('The style of the image.'),
        '#default_value' => $settings['style'],
        '#options' => $options,
      );
      $element['caption'] = array(
        '#type' => 'checkbox',
        '#description' => t('The caption uses the alt text of the image field.'),
        '#title' => t('Enable caption.'),
        '#default_value' => $settings['caption'],
      );
      $element['likes'] = array(
        '#type' => 'checkbox',
        '#title' => t('Enable Facebook Likes. (data-feedback)'),
        '#default_value' => $settings['likes'],
      );
      $element['comments'] = array(
        '#type' => 'checkbox',
        '#title' => t('Enable Facebook Comments. (data-feedback)'),
        '#default_value' => $settings['comments'],
      );
      $element['fullscreen'] = array(
        '#type' => 'checkbox',
        '#title' => t('Enable Fullscreen.'),
        '#default_value' => $settings['fullscreen'],
      );
      break;

    case 'fbia_analytics_formatter':
      $element['source'] = array(
        '#type' => 'select',
        '#title' => t('Source'),
        '#description' => t('Add your tracker specifying the URL or embed the full unescaped HTML.'),
        '#default_value'  => $settings['source'],
        '#options' => array(
          'url' => t('Ad URL'),
          'embed' => t('Embedded HTML'),
        ),
      );
      break;

  }

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function fb_instant_articles_display_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $summary = '';
  switch ($display['type']) {
    case 'fbia_ad_formatter':
      $summary = t('Ad field - set the Source, iFrame height (@height) and width (@width).', array(
        '@height' => $settings['height'],
        '@width' => $settings['width'],
      ));
      break;

    case 'fbia_interactive_formatter':
      $summary = t('Interactive field - set iFrame height (@height) and width (@width).', array(
        '@height' => $settings['height'],
        '@width' => $settings['width'],
      ));
      break;

    case 'fbia_analytics_formatter':
      $summary = t('Analytics field - set the Source of the iframe. (@source)', array(
        '@source' => $settings['source'],
      ));
      break;

    case 'fbia_image_formatter':
      $summary = t('Image field - Style:(@style)', array(
        '@style' => $settings['style'],
      ));
      break;

    case 'fbia_list_formatter':
      $summary = t('List field - Type:(@list_type)', array(
        '@list_type' => $settings['list_type'],
      ));
      break;
  }
  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function fb_instant_articles_display_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  module_load_include('inc', 'fb_instant_articles_display', 'includes/elements');
  $element = array();
  $settings = $display['settings'];

  // Grab the InstantArticle object we're going to be building up.  If it's not
  // present, it means that a site admin selected an FB IA field formatter for
  // a non-FB IA content type.
  if (isset($entity->fb_instant_articles_display_instant_article)) {
    /** @var InstantArticle $instant_article */
    $instant_article = $entity->fb_instant_articles_display_instant_article;
    $active_region = 'none';
    /** @var Header $header */
    $header = $instant_article->getHeader();
    /** @var Footer $footer */
    $footer = $instant_article->getFooter();

    // Determine which region this field belongs to.
    $regions = $entity->fb_instant_articles_display_layout_settings->settings['regions'];
    foreach ($regions as $region => $fields) {
      if (in_array($field['field_name'], $fields)) {
        $active_region = $region;
        break;
      }
    }

    // We might not have added a footer. If the active region is a footer,
    // ensure it exists before continuing.
    if ($active_region === 'footer' && empty($footer)) {
      $footer = Footer::create();
      $instant_article->withFooter($footer);
    }

    // For each FBIA formatter, place according to the set region, only if it
    // actually makes sense.  ie you can't put a Kicker into the footer.
    switch ($display['type']) {
      case 'fbia_subtitle_formatter':
        if ($active_region === 'header') {
          fb_instant_articles_display_field_format_subtitle($items, $header);
        }
        break;
      case 'fbia_kicker_formatter':
        if ($active_region === 'header') {
          fb_instant_articles_display_field_format_kicker($items, $header);
        }
        break;
      case 'fbia_author_formatter':
        if ($active_region === 'header') {
          fb_instant_articles_display_field_format_author($items, $header);
        }
        break;
      case 'fbia_ad_formatter':
        if ($active_region === 'header') {
          fb_instant_articles_display_field_format_ad_element($items, $header, $settings);
        }
        break;
      case 'fbia_image_formatter':
        // Images are only allowed in the header and body.
        $pass_region = null;
        if ($active_region === 'header') {
          $pass_region = $header;
        }
        elseif ($active_region === 'body') {
          $pass_region = $instant_article;
        }
        if ($pass_region) {
          fb_instant_articles_display_field_format_image_element($items, $pass_region, $settings);
        }
        break;
      case 'fbia_blockquote_formatter':
        if ($active_region === 'body') {
          fb_instant_articles_display_field_format_text_container($items, $instant_article, Blockquote::create());
        }
        break;
      case 'fbia_pullquote_formatter':
        if ($active_region === 'body') {
          fb_instant_articles_display_field_format_text_container($items, $instant_article, PullQuote::create());
        }
        break;
      case 'fbia_analytics_formatter':
        if ($active_region === 'body') {
          fb_instant_articles_display_field_format_analytics_element($items, $instant_article, $settings);
        }
        break;
      case 'fbia_credits_formatter':
        if ($active_region === 'footer') {
          fb_instant_articles_display_field_format_credits($items, $footer);
        }
        break;
      case 'fbia_copyright_formatter':
        if ($active_region === 'footer') {
          fb_instant_articles_display_field_format_copyright($items, $footer);
        }
        break;

      // @todo convert the rest of these to use InstantArticle object
      case 'fbia_video_formatter':
        $element = fb_instant_articles_display_field_format_video_element($items, $settings);
        break;

      case 'fbia_interactive_formatter':
        $element = fb_instant_articles_display_field_format_interactive_element($items, $settings);
        break;

      case 'fbia_list_formatter':
        $element = fb_instant_articles_display_field_format_list_element($items, $settings);
        break;

      case 'fbia_social_formatter':
        $element = fb_instant_articles_display_field_format_social_element($items, $settings);
        break;
    }
    return $element;
  }
}

/**
 * Remove formatters from view modes which are not Facebook Instant Articles.
 */
function fb_instant_articles_display_cleanup_view_mode_formatters(&$form) {
  foreach ($form['fields'] as $field_key => $field) {
    if (strpos($field_key, '#') === FALSE) {
      foreach ($field['format']['type']['#options'] as $format_key => $format) {
        if (strpos($format_key, 'fbia') !== FALSE) {
          unset($form['fields'][$field_key]['format']['type']['#options'][$format_key]);
        }
      }
    }
  }
}

/**
 * Format time elements.
 */
function fb_instant_articles_display_time_element($timestamp, $class) {
  $class = ' class="' . $class . '"';

  $date = new DateTime("@$timestamp");
  $datetime = ' datetime="' . $date->format(DateTime::ATOM) . '"';
  $text_time = $date->format('F jS, g:i A');
  $element = '<time' . $class . $datetime . '>' . $text_time . '</time>';

  return $element;
}
