<?php

/**
 * @file
 * Hook implementations for Facebook Instant Articles API module.
 */

/**
 * Implements hook_menu().
 */
function fb_instant_articles_api_menu() {
  $items['admin/config/services/fb-instant-articles/api'] = array(
    'title' => 'Facebook Instant Articles API',
    'description' => 'API settings for Facebook Instant Articles.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fb_instant_articles_api_settings'),
    'access arguments' => array('administer fb_instant_articles_api'),
    'file' => 'includes/admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function fb_instant_articles_api_permission() {
  $permissions = array();

  $permissions['administer fb_instant_articles_api'] = array(
    'title' => t('Administer Facebook Instant Articles API'),
  );
  return $permissions;
}
