<?php

/**
 * @file
 * Facebook Instant Articles RSS module.
 */

/**
 * Implements hook_menu().
 */
function fb_instant_articles_rss_menu() {
  $items['fbinstant.rss'] = array(
    'description' => 'Facebook Instant Articles RSS endpoint',
    'page callback' => 'fb_instant_articles_rss_page',
    'file' => 'includes/rss.inc',
    'access arguments' => array('access content'),
  );

  $items['admin/config/services/fb-instant-articles/rss'] = array(
    'title' => 'Facebook Instant Articles RSS',
    'description' => 'RSS settings for Facebook Instant Articles.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('fb_instant_articles_rss_settings'),
    'access arguments' => array('administer fb_instant_articles_rss'),
    'file' => 'includes/admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function fb_instant_articles_rss_permission() {
  $permissions = array();

  $permissions['administer fb_instant_articles_rss'] = array(
    'title' => t('Administer Facebook Instant Articles RSS'),
  );
  return $permissions;
}

/**
 * Implements hook_node_operations().
 */
function fb_instant_articles_rss_node_operations() {
  // Check for setting "All nodes enabled by default?".
  // Only show additional operations if setting is not set.
  $fia_all_enabled = variable_get('fb_instant_articles_rss_all_enabled_default', TRUE);
  if (!$fia_all_enabled) {
    $operations = array(
      'add_fia' => array(
        'label' => t('Publish selected content to Facebook Instant Articles RSS feed'),
        'callback' => 'fb_instant_articles_mass_update',
        'callback arguments' => array('fia_enabled' => 1),
      ),
      'remove_fia' => array(
        'label' => t('Unpublish selected content from Facebook Instant Articles RSS feed'),
        'callback' => 'fb_instant_articles_rss_mass_update',
        'callback arguments' => array('fia_enabled' => 0),
      ),
    );
  }
  return $operations;
}

/**
 * Makes mass update of fia_enabled status for selected nodes.
 *
 * @param array $nodes
 *   Array of node nids to update.
 * @param boolean $fia_enabled
 *   Boolean indicating publishing status of node.
 */
function fb_instant_articles_rss_mass_update($nodes, $fia_enabled) {
  // We need node objects here to retrieve content type and it's fia settings.
  $load_nodes = entity_load('node', array_keys($nodes));
  $fia_types = fb_instant_articles_display_get_article_entity_types();
  foreach ($load_nodes as $node) {
    if (in_array($node->type, array_keys($fia_types['node']))) {
      if ($fia_enabled) {
        fb_instant_articles_rss_set_entity($node->nid, $fia_enabled);
      }
      else {
        fb_instant_articles_rss_delete_entity($node->nid);
      }
    }
  }
  drupal_set_message(t('Selected nodes where %action Facebook Instant Articles RSS feed.', array(
    '%action' => ($fia_enabled) ? t('published on') : t('unpublished from'),
  )));
}

/**
 * Boolean check to see if a given entity id is a product type.
 *
 * @param string $entity_id
 *   The entity id.
 *
 * @return bool
 *   Boolean TRUE or FALSE.
 */
function fb_instant_articles_rss_is_article($entity_id) {
  $is_type = FALSE;
  $results = db_select('fb_instant_articles_rss_entity_settings', 'fiaes')
    ->fields('fiaes', array('fia_enabled'))
    ->condition('entity_id', $entity_id)
    ->execute();
  if (!$results->rowCount()) {
    $is_type = variable_get('fb_instant_articles_rss_all_enabled_default', TRUE);
  }
  else {
    $is_type = $results->fetch()->fia_enabled;
  }
  // Allow other modules to alter.
  drupal_alter('fb_instant_articles_rss_is_article', $is_type, $entity_id);

  return $is_type;
}

/**
 * Save the product id field for an entity.
 *
 * @param int $id
 *   The entity id.
 */
function fb_instant_articles_rss_set_entity($id, $enabled) {
  db_merge('fb_instant_articles_rss_entity_settings')
    ->key(array('entity_id' => $id))
    ->fields(array(
      'entity_id' => $id,
      'fia_enabled' => $enabled,
    ))
    ->execute();
  // Allow other modules to perform actions.
  module_invoke_all('fb_instant_articles_rss_set_entity', $id, $enabled);
}

/**
 * Delete the field set to be used as the product id for entity.
 *
 * @param string $id
 *   The entity id.
 */
function fb_instant_articles_rss_delete_entity($id) {
  db_delete('fb_instant_articles_rss_entity_settings')
    ->condition('entity_id', $id)
    ->execute();
  // Allow other modules to perform actions.
  module_invoke_all('fb_instant_articles_rss_delete_entity', $id);
}
