<?php

/**
 * @file
 * Update and install functions for Facebook Instant Articles RSS module.
 */

/**
 * Implements hook_uninstall().
 */
function fb_instant_articles_rss_uninstall() {
  variable_del('fb_instant_articles_rss_channel_title');
  variable_del('fb_instant_articles_rss_channel_description');
  variable_del('fb_instant_articles_rss_channel_language');
  variable_del('fb_instant_articles_rss_style');
  variable_del('fb_instant_articles_rss_number_results_in_feed');
  variable_del('fb_instant_articles_rss_all_enabled_default');
}
