<?php

/**
 * @file
 * Contains fb_instant_articles_views.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fb_instant_articles_views_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the fb_instant_articles_views module.
    case 'help.page.fb_instant_articles_views':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Facebook Instant Articles RSS feed generator.') . '</p>';
      return $output;
  }
}
