<?php

/**
 * @file
 * Facebook instant articles primary module file.
 *
 * This is the main module file for fb_instant_articles_views.
 */


/**
 * Implements hook_help().
 */
function fb_instant_articles_views_help($path, $arg) {
  switch ($path) {
    // Main module help for the fb_instant_articles_views module.
    case 'admin/help#fb_instant_articles_views':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('FB Instant articles RSS feed generator for integration into the FB IA program') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_views_api().
 */
function fb_instant_articles_views_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'fb_instant_articles_views') . '/views',
  );
}

