<?php

/**
 * @file
 * Provide Drupal rules to manage facebook instant article using API.
 */

/**
 * Implements hook_action_info().
 *
 * @todo - Convert this entire module to support entity instead of only Node.
 *
 */
function fb_instant_articles_api_rules_action_info() {
  return array(
    'facebook_instant_articles_api_import_action' => array(
      'type' => 'node',
      'label' => t('Add facebook instant article'),
      'configurable' => FALSE,
      'triggers' => array(
        'node_presave', 'node_insert', 'node_update',
      ),
    ),
    'facebook_instant_articles_api_remove_action' => array(
      'type' => 'node',
      'label' => t('Delete facebook instant article'),
      'configurable' => FALSE,
      'triggers' => array(
        'node_delete',
      ),
    ),
  );
}


/**
 * Implementation of a Facebook instant article node import action.
 *
 */
function facebook_instant_articles_api_import_action($node, $context = array()) {
  $fb_instant_enabled = fb_instant_articles_display_is_article_type('node', $node);
  if($fb_instant_enabled) {
    fb_instant_articles_api_rules_import_article($node);
  }
}


/**
 * Implementation of a Facebook instant article node delete action.
 *
 */
function facebook_instant_articles_api_remove_action($node, $context = array()) {
  $fb_instant_enabled = fb_instant_articles_display_is_article_type('node', $node);
  if($fb_instant_enabled) {
    fb_instant_articles_api_rules_remove_article($node);
  }
}

/**
 * Implementation of a Facebook instant article import.
 *
 * @param object $node
 */
function fb_instant_articles_api_rules_import_article($node) {
  if (isset($node->nid)) {
    $article = $node->fb_instant_articles_display_wrapper;
    \Drupal\fb_instant_articles_api\Client::create()->importArticle($article, $node->status);
  }
}

/**
 * Implementation of a Facebook instant article remove.
 *
 * @param object $node
 */
function fb_instant_articles_api_rules_remove_article($node) {
  if (isset($node->nid)) {
    $url = url(drupal_get_path_alias("node/" . $node->nid), array('absolute' => TRUE));
    \Drupal\fb_instant_articles_api\Client::create()->removeArticle($url);
  }
}
